- apiVersion: v1
  kind: Namespace
  metadata:
    name: default-1652164540601
  spec:
    finalizers:
      - kubernetes
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nodeapp-test-db
    namespace: default-1652164540601
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: nodeapp-test-db
    template:
      metadata:
        labels:
          app: nodeapp-test-db
      spec:
        nodeSelector:
          kubernetes.io/os: linux
        containers:
          - name: nodeapp-test-db
            image: mopicnodeappacr.azurecr.io/nodeapp_test_db:de1
            ports:
              - containerPort: 3001
            resources:
              requests:
                cpu: '0'
                memory: '0'
              limits:
                cpu: '256'
                memory: 11400G
- apiVersion: v1
  kind: Service
  metadata:
    name: nodeapp-test-db-service
    namespace: default-1652164540601
  spec:
    type: LoadBalancer
    ports:
      - targetPort: 3001
        name: port3001
        port: 3001
        protocol: TCP
    selector:
      app: nodeapp-test-db