name: github_action_push

on:
  push:
    branches:
      - "main"

jobs:
  build-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: DockerBuild
        run: docker build --pull --rm -f "Dockerfile" -t nodeapptestdb:latest "."