name: github_with_aks

on:
  push:
    branches:
      - "main"

jobs:
  login-aks:
    runs-on: ubuntu-latest
    steps:
      # Logs in with your Azure credentials
    - name: Azure login
      uses: azure/login@v1.4.3
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}